import {
  CustomerReport,
  DedicatedDiscountCodeReport,
  DedicatedLinkReport,
  FinancialRecord,
  FinancialRecordStatus,
  FinancialRecordType,
} from "@/shared/types";
import {
  CurrentAdminUser,
  AdminUserRole,
  Order,
  OrderCancelReason,
  OrderStatus,
  PaymentMethod,
  PostageMethod,
  PrintColor,
  PrintSize,
  PrintSide,
  Address,
  User,
  TransactionStatus,
  Transaction,
  DiscountType,
  CooperationRequest,
  CooperationRequestStatus,
  DiscountCode,
  WithdrawalRequest,
  WithdrawalRequestStatus,
  BindingType,
  AllPrintPrices,
} from "@/shared/types";

export const currentUser: CurrentAdminUser = {
  name: "عباس بوعذار",
  phoneNumber: "09359278399",
  avatar: null,
  role: AdminUserRole.admin,
};

export const orders: Order[] = [
  {
    id: "265454",
    status: OrderStatus.sent,
    cancelReason: null,
    printFolders: [
      {
        printFiles: [
          {
            id: "1",
            name: "جزوه مدار-1.pdf",
          },
          {
            id: "2",
            name: "جزوه مدار-2.pdf",
          },
        ],
        printColor: PrintColor.normalColor,
        printSize: PrintSize.a4,
        printSide: PrintSide.doubleSided,
        countOfPages: 500,
        bindingOptions: null,
        description:
          "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی و فرهنگ پیشرو در زبان فارسی ایجاد کرد. در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای اصلی و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.",
        numberOfCopies: null,
      },
    ],
    recipientName: "آرش زنگنه فر",
    recipientPhoneNumber: "0123456789",
    recipientPostalCode: "1234512345",
    date: new Date("2022-07-11T07:24:52"),
    recipientDeliveryAddress:
      "استان اصفهان / شهر اصفهان / خیابان 1 / خیابان 2 / کوچه 1 / پلاک 1 / طبقه 1",
    amount: 650000,
    postageAmount: 200000,
    discountAmount: 20000,
    discountCode: "HHFDPD",
    paymentMethod: {
      [PaymentMethod.zarinPalGate]: 30000,
      [PaymentMethod.wallet]: 600000,
    },
    lastStatusChange: new Date("2022-07-13T07:24:52"),
    trackingCode: "102489911100422150000114",
    postageDate: new Date("2022-07-13T07:24:52"),
    postageMethod: PostageMethod.expressMail,
  },
  {
    id: "12345",
    status: OrderStatus.preparing,
    cancelReason: null,
    printFolders: [
      {
        printFiles: [
          {
            id: "1",
            name: "جزوه مدار-1.pdf",
          },
          {
            id: "2",
            name: "جزوه مدار-2.pdf",
          },
        ],
        printColor: PrintColor.normalColor,
        printSize: PrintSize.a4,
        printSide: PrintSide.doubleSided,
        countOfPages: 500,
        bindingOptions: null,
        description:
          "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی و فرهنگ پیشرو در زبان فارسی ایجاد کرد. در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای اصلی و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.",
        numberOfCopies: null,
      },
    ],
    recipientName: "آرش زنگنه فر",
    recipientPhoneNumber: "0123456789",
    recipientPostalCode: "1234512345",
    date: new Date("2022-07-11T07:24:52"),
    recipientDeliveryAddress:
      "استان اصفهان / شهر اصفهان / خیابان 1 / خیابان 2 / کوچه 1 / پلاک 1 / طبقه 1",
    amount: 650000,
    postageAmount: 200000,
    discountAmount: 20000,
    discountCode: "HHFDPD",
    paymentMethod: {
      [PaymentMethod.zarinPalGate]: 30000,
      [PaymentMethod.wallet]: 600000,
    },
    lastStatusChange: new Date("2022-07-13T07:24:52"),
    trackingCode: "102489911100422150000114",
    postageDate: new Date("2022-07-13T07:24:52"),
    postageMethod: PostageMethod.expressMail,
  },
  {
    id: "56789",
    status: OrderStatus.pending,
    cancelReason: null,
    printFolders: [
      {
        printFiles: [
          {
            id: "1",
            name: "جزوه مدار-1.pdf",
          },
          {
            id: "2",
            name: "جزوه مدار-2.pdf",
          },
        ],
        printColor: PrintColor.normalColor,
        printSize: PrintSize.a4,
        printSide: PrintSide.doubleSided,
        countOfPages: 500,
        bindingOptions: null,
        description:
          "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی و فرهنگ پیشرو در زبان فارسی ایجاد کرد. در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای اصلی و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.",
        numberOfCopies: null,
      },
    ],
    recipientName: "آرش زنگنه فر",
    recipientPhoneNumber: "0123456789",
    recipientPostalCode: "1234512345",
    date: new Date("2022-07-11T07:24:52"),
    recipientDeliveryAddress:
      "استان اصفهان / شهر اصفهان / خیابان 1 / خیابان 2 / کوچه 1 / پلاک 1 / طبقه 1",
    amount: 650000,
    postageAmount: 200000,
    discountAmount: 20000,
    discountCode: "HHFDPD",
    paymentMethod: {
      [PaymentMethod.zarinPalGate]: 30000,
      [PaymentMethod.wallet]: 600000,
    },
    lastStatusChange: new Date("2022-07-13T07:24:52"),
    trackingCode: "102489911100422150000114",
    postageDate: new Date("2022-07-13T07:24:52"),
    postageMethod: PostageMethod.expressMail,
  },
  {
    id: "123789",
    status: OrderStatus.canceled,
    cancelReason: OrderCancelReason.userCancel,
    printFolders: [
      {
        printFiles: [
          {
            id: "1",
            name: "جزوه مدار-1.pdf",
          },
          {
            id: "2",
            name: "جزوه مدار-2.pdf",
          },
        ],
        printColor: PrintColor.normalColor,
        printSize: PrintSize.a4,
        printSide: PrintSide.doubleSided,
        countOfPages: 500,
        bindingOptions: null,
        description:
          "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی و فرهنگ پیشرو در زبان فارسی ایجاد کرد. در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای اصلی و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.",
        numberOfCopies: null,
      },
    ],
    recipientName: "آرش زنگنه فر",
    recipientPhoneNumber: "0123456789",
    recipientPostalCode: "1234512345",
    date: new Date("2022-07-11T07:24:52"),
    recipientDeliveryAddress:
      "استان اصفهان / شهر اصفهان / خیابان 1 / خیابان 2 / کوچه 1 / پلاک 1 / طبقه 1",
    amount: 650000,
    postageAmount: 200000,
    discountAmount: 20000,
    discountCode: "HHFDPD",
    paymentMethod: {
      [PaymentMethod.zarinPalGate]: 30000,
      [PaymentMethod.wallet]: 600000,
    },
    lastStatusChange: new Date("2022-07-13T07:24:52"),
    trackingCode: "102489911100422150000114",
    postageDate: new Date("2022-07-13T07:24:52"),
    postageMethod: PostageMethod.expressMail,
  },
  {
    id: "456134",
    status: OrderStatus.canceled,
    cancelReason: OrderCancelReason.countOfPagesMismatch,
    printFolders: [
      {
        printFiles: [
          {
            id: "1",
            name: "جزوه مدار-1.pdf",
          },
          {
            id: "2",
            name: "جزوه مدار-2.pdf",
          },
        ],
        printColor: PrintColor.normalColor,
        printSize: PrintSize.a4,
        printSide: PrintSide.doubleSided,
        countOfPages: 500,
        bindingOptions: null,
        description:
          "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی و فرهنگ پیشرو در زبان فارسی ایجاد کرد. در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای اصلی و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.",
        numberOfCopies: null,
      },
    ],
    recipientName: "آرش زنگنه فر",
    recipientPhoneNumber: "0123456789",
    recipientPostalCode: "1234512345",
    date: new Date("2022-07-11T07:24:52"),
    recipientDeliveryAddress:
      "استان اصفهان / شهر اصفهان / خیابان 1 / خیابان 2 / کوچه 1 / پلاک 1 / طبقه 1",
    amount: 650000,
    postageAmount: 200000,
    discountAmount: 20000,
    discountCode: "HHFDPD",
    paymentMethod: {
      [PaymentMethod.zarinPalGate]: 30000,
      [PaymentMethod.wallet]: 600000,
    },
    lastStatusChange: new Date("2022-07-13T07:24:52"),
    trackingCode: "102489911100422150000114",
    postageDate: new Date("2022-07-13T07:24:52"),
    postageMethod: PostageMethod.expressMail,
  },
];

export const addresses: Address[] = [
  {
    id: "1",
    label: "خانه",
    recipientName: "آرش زنگنه فر",
    recipientPhoneNumber: "0123456789",
    recipientPostalCode: "1234512345",
    recipientDeliveryProvince: "اصفهان",
    recipientDeliveryCity: "اصفهان",
    recipientDeliveryAddress: "خیابان 1 / خیابان 2 / کوچه 1 / پلاک 1 / طبقه 1",
  },
  {
    id: "2",
    label: "مدرسه",
    recipientName: "آرش زنگنه فر",
    recipientPhoneNumber: "0123456789",
    recipientPostalCode: "1234512345",
    recipientDeliveryProvince: "اصفهان",
    recipientDeliveryCity: "اصفهان",
    recipientDeliveryAddress: "خیابان 1 / خیابان 2 / کوچه 1 / پلاک 1 / طبقه 1",
  },
];

export const transactions: Transaction[] = [
  {
    id: "1",
    date: new Date("2022-05-06T07:24"),
    amount: 14500000,
    details: "",
    orderId: "265454",
    status: TransactionStatus.successful,
  },
  {
    id: "2",
    date: new Date("2022-05-06T07:24"),
    amount: 14500000,
    details: "پکیج دانشجویی",
    orderId: null,
    status: TransactionStatus.successful,
  },
  {
    id: "3",
    date: new Date("2022-05-06T07:24"),
    amount: 14500000,
    details: "بازگشت وجه به کیف پول بابت لغو سفارش",
    orderId: null,
    status: TransactionStatus.successful,
  },
  {
    id: "4",
    date: new Date("2022-05-06T07:24"),
    amount: 14500000,
    details: "",
    orderId: "265454",
    status: TransactionStatus.unsuccessful,
  },
  {
    id: "5",
    date: new Date("2022-05-06T07:24"),
    amount: 14500000,
    details: "افزایش موجودی کیف پول",
    orderId: null,
    status: TransactionStatus.unsuccessful,
  },
  {
    id: "6",
    date: new Date("2022-05-06T07:24"),
    amount: 14500000,
    details: "واریز به حساب کاربر بابت برداشت موجودی کد پیگیری :1542552",
    orderId: null,
    status: TransactionStatus.successful,
  },
  {
    id: "7",
    date: new Date("2022-05-06T07:24"),
    amount: 14500000,
    details: "5 درصد پورسانت بازاریابی با کد تخفیف",
    orderId: null,
    status: TransactionStatus.successful,
  },
];

export const users: User[] = [
  {
    id: "1123",
    name: "عباس بوعذار اصل اصفهانی",
    phoneNumber: "09359278399",
    avatar: null,
    wallet: {
      balance: 1220000,
      marketingSales: 180000,
    },
    orders,
    addresses,
    transactions,
  },
  {
    id: "1345",
    name: "عباس بوعذار اصل اصفهانی",
    phoneNumber: "09359278399",
    avatar: null,
    wallet: {
      balance: 1220000,
      marketingSales: 180000,
    },
    orders,
    addresses,
    transactions,
  },
  {
    id: "8564",
    name: "عباس بوعذار اصل اصفهانی",
    phoneNumber: "09359278399",
    avatar: null,
    wallet: {
      balance: 1220000,
      marketingSales: 180000,
    },
    orders,
    addresses,
    transactions,
  },
  {
    id: "1456",
    name: "عباس بوعذار اصل اصفهانی",
    phoneNumber: "09359278399",
    avatar: null,
    wallet: {
      balance: 1220000,
      marketingSales: 180000,
    },
    orders,
    addresses,
    transactions,
  },
];

export const discountCodes: DiscountCode[] = [
  {
    id: "1",
    active: false,
    code: "YALDA1401",
    description: "تخفیف شگفت انگیز به مناسب شب یلدا",
    customer: null,
    discountType: DiscountType.fixedAmount,
    discountValue: 5000,
    percentageDiscountCeiling: null,
    minOrderAmount: null,
    maxOrderAmount: null,
    minPageCount: 50,
    maxPageCount: 70,
    usageLimit: null,
    timesUsed: null,
    expirationDate: new Date("2022-07-13T07:24:52"),
  },
  {
    id: "2",
    active: true,
    code: "YALDA1402",
    description: "تخفیف شگفت انگیز به مناسب شب یلدا",
    customer: null,
    discountType: DiscountType.percentage,
    discountValue: 50,
    percentageDiscountCeiling: null,
    minOrderAmount: null,
    maxOrderAmount: null,
    minPageCount: 50,
    maxPageCount: null,
    usageLimit: 20,
    timesUsed: 11,
    expirationDate: null,
  },
  {
    id: "3",
    active: false,
    code: "YALDA1403",
    description: "تخفیف شگفت انگیز به مناسب شب یلدا",
    customer: null,
    discountType: DiscountType.numberOfPages,
    discountValue: 50,
    percentageDiscountCeiling: null,
    minOrderAmount: null,
    maxOrderAmount: null,
    minPageCount: null,
    maxPageCount: 70,
    usageLimit: null,
    timesUsed: null,
    expirationDate: null,
  },
  {
    id: "4",
    active: true,
    code: "YALDA1404",
    description: "تخفیف شگفت انگیز به مناسب شب یلدا",
    customer: null,
    discountType: DiscountType.fixedAmount,
    discountValue: 50000,
    percentageDiscountCeiling: null,
    minOrderAmount: 100000,
    maxOrderAmount: null,
    minPageCount: null,
    maxPageCount: null,
    usageLimit: null,
    timesUsed: null,
    expirationDate: null,
  },
  {
    id: "5",
    active: true,
    code: "YALDA1405",
    description: "تخفیف شگفت انگیز به مناسب شب یلدا",
    customer: null,
    discountType: DiscountType.fixedAmount,
    discountValue: 50000,
    percentageDiscountCeiling: null,
    minOrderAmount: null,
    maxOrderAmount: 200000,
    minPageCount: null,
    maxPageCount: null,
    usageLimit: null,
    timesUsed: null,
    expirationDate: null,
  },
  {
    id: "6",
    active: true,
    code: "YALDA1406",
    description: "تخفیف شگفت انگیز به مناسب شب یلدا",
    customer: null,
    discountType: DiscountType.fixedAmount,
    discountValue: 50000,
    percentageDiscountCeiling: null,
    minOrderAmount: 100000,
    maxOrderAmount: 200000,
    minPageCount: null,
    maxPageCount: null,
    usageLimit: null,
    timesUsed: null,
    expirationDate: null,
  },
];

export const cooperationRequests: CooperationRequest[] = [
  {
    id: "1",
    phoneNumber: "09359278399",
    date: new Date("2022-07-13T07:24:52"),
    description: null,
    status: CooperationRequestStatus.pending,
  },
  {
    id: "2",
    phoneNumber: "09359278399",
    date: new Date("2022-07-13T07:24:52"),
    description:
      "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی و فرهنگ پیشرو در زبان فارسی ایجاد کرد. در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای اصلی و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.",
    status: CooperationRequestStatus.accepted,
  },
  {
    id: "3",
    phoneNumber: "09359278399",
    date: new Date("2022-07-13T07:24:52"),
    description:
      "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی و فرهنگ پیشرو در زبان فارسی ایجاد کرد. در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای اصلی و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.",
    status: CooperationRequestStatus.accepted,
  },
  {
    id: "4",
    phoneNumber: "09359278399",
    date: new Date("2022-07-13T07:24:52"),
    description:
      "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی و فرهنگ پیشرو در زبان فارسی ایجاد کرد. در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای اصلی و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.",
    status: CooperationRequestStatus.rejected,
  },
];

export const financialRecords: FinancialRecord[] = [
  {
    id: "1",
    user: users[0],
    date: new Date("2022-07-13T07:24:52"),
    amount: 50000,
    details: "",
    orderId: "265454",
    type: FinancialRecordType.creditor,
    status: FinancialRecordStatus.successful,
    addedBy: null,
  },
  {
    id: "2",
    user: users[1],
    date: new Date("2022-07-13T07:24:52"),
    amount: 50000,
    details: "پکیج دانشجویی",
    orderId: null,
    type: FinancialRecordType.creditor,
    status: FinancialRecordStatus.successful,
    addedBy: null,
  },
  {
    id: "3",
    user: users[2],
    date: new Date("2022-07-13T07:24:52"),
    amount: 50000,
    details: "بازگشت وجه به کیف پول بابت لغو سفارش",
    orderId: null,
    type: FinancialRecordType.debtor,
    status: FinancialRecordStatus.addedManually,
    addedBy: {
      id: "1",
      avatar: null,
      name: "عباس بوعذار",
      phoneNumber: "09359278399",
      role: AdminUserRole.representation,
    },
  },
  {
    id: "4",
    user: users[3],
    date: new Date("2022-07-13T07:24:52"),
    amount: 50000,
    details: "",
    orderId: "265454",
    type: FinancialRecordType.debtor,
    status: FinancialRecordStatus.unsuccessful,
    addedBy: null,
  },
  {
    id: "5",
    user: users[3],
    date: new Date("2022-07-13T07:24:52"),
    amount: 50000,
    details: "افزایش موجودی کیف پول",
    orderId: null,
    type: FinancialRecordType.debtor,
    status: FinancialRecordStatus.successful,
    addedBy: null,
  },
  {
    id: "6",
    user: users[3],
    date: new Date("2022-07-13T07:24:52"),
    amount: 50000,
    details: "واریز به حساب کاربر بابت برداشت موجودی کد پیگیری :1542552",
    orderId: null,
    type: FinancialRecordType.creditor,
    status: FinancialRecordStatus.successful,
    addedBy: null,
  },
  {
    id: "7",
    user: users[3],
    date: new Date("2022-07-13T07:24:52"),
    amount: 50000,
    details: "5 درصد پورسانت بازاریابی با کد تخفیف",
    orderId: null,
    type: FinancialRecordType.creditor,
    status: FinancialRecordStatus.unsuccessful,
    addedBy: null,
  },
];

export const withdrawalRequests: WithdrawalRequest[] = [
  {
    id: "1",
    user: users[0],
    date: new Date("2022-07-13T07:24:52"),
    amount: 50000,
    shabaNumber: 840610000000700790111111,
    accountHolderName: "عباس بوعذار اصل اصفهانی",
    rejectReason: null,
    transactionDate: null,
    transactionTrackingCode: null,
    status: WithdrawalRequestStatus.pending,
  },
  {
    id: "2",
    user: users[1],
    date: new Date("2022-07-13T07:24:52"),
    amount: 50000,
    shabaNumber: 840610000000700790111111,
    accountHolderName: "عباس بوعذار اصل اصفهانی",
    rejectReason: null,
    transactionDate: "2022-07-13",
    transactionTrackingCode: "525500254112",
    status: WithdrawalRequestStatus.done,
  },
  {
    id: "3",
    user: users[2],
    date: new Date("2022-07-13T07:24:52"),
    amount: 50000,
    shabaNumber: 840610000000700790111111,
    accountHolderName: "عباس بوعذار اصل اصفهانی",
    rejectReason: null,
    transactionDate: "2022-07-13",
    transactionTrackingCode: "525500254112",
    status: WithdrawalRequestStatus.done,
  },
  {
    id: "4",
    user: users[3],
    date: new Date("2022-07-13T07:24:52"),
    amount: 50000,
    shabaNumber: 840610000000700790111111,
    accountHolderName: "عباس بوعذار اصل اصفهانی",
    rejectReason: "عدم تطابق شماره شبا با نام حساب",
    transactionDate: null,
    transactionTrackingCode: null,
    status: WithdrawalRequestStatus.rejected,
  },
];

export const allPrintPrices: AllPrintPrices = {
  [PrintSize.a4]: {
    [PrintColor.blackAndWhite]: {
      [PrintSide.singleSided]: 480,
      [PrintSide.doubleSided]: 620,
      [PrintSide.singleSidedGlossy]: 0,
      [PrintSide.doubleSidedGlossy]: 0,
      breakpoints: [
        {
          at: 501,
          [PrintSide.singleSided]: 460,
          [PrintSide.doubleSided]: 580,
          [PrintSide.singleSidedGlossy]: 0,
          [PrintSide.doubleSidedGlossy]: 0,
        },
        {
          at: 1001,
          [PrintSide.singleSided]: 430,
          [PrintSide.doubleSided]: 560,
          [PrintSide.singleSidedGlossy]: 0,
          [PrintSide.doubleSidedGlossy]: 0,
        },
      ],
    },
    [PrintColor.normalColor]: {
      [PrintSide.singleSided]: 480,
      [PrintSide.doubleSided]: 620,
      [PrintSide.singleSidedGlossy]: 0,
      [PrintSide.doubleSidedGlossy]: 0,
      breakpoints: [
        {
          at: 501,
          [PrintSide.singleSided]: 460,
          [PrintSide.doubleSided]: 580,
          [PrintSide.singleSidedGlossy]: 0,
          [PrintSide.doubleSidedGlossy]: 0,
        },
        {
          at: 1001,
          [PrintSide.singleSided]: 430,
          [PrintSide.doubleSided]: 560,
          [PrintSide.singleSidedGlossy]: 0,
          [PrintSide.doubleSidedGlossy]: 0,
        },
      ],
    },
    [PrintColor.fullColor]: {
      [PrintSide.singleSided]: 480,
      [PrintSide.doubleSided]: 620,
      [PrintSide.singleSidedGlossy]: 0,
      [PrintSide.doubleSidedGlossy]: 0,
      breakpoints: [
        {
          at: 501,
          [PrintSide.singleSided]: 460,
          [PrintSide.doubleSided]: 580,
          [PrintSide.singleSidedGlossy]: 0,
          [PrintSide.doubleSidedGlossy]: 0,
        },
        {
          at: 1001,
          [PrintSide.singleSided]: 430,
          [PrintSide.doubleSided]: 560,
          [PrintSide.singleSidedGlossy]: 0,
          [PrintSide.doubleSidedGlossy]: 0,
        },
      ],
    },
  },
  [PrintSize.a3]: {
    [PrintColor.blackAndWhite]: {
      [PrintSide.singleSided]: 480,
      [PrintSide.doubleSided]: 620,
      [PrintSide.singleSidedGlossy]: 0,
      [PrintSide.doubleSidedGlossy]: 0,
      breakpoints: [
        {
          at: 501,
          [PrintSide.singleSided]: 460,
          [PrintSide.doubleSided]: 580,
          [PrintSide.singleSidedGlossy]: 0,
          [PrintSide.doubleSidedGlossy]: 0,
        },
        {
          at: 1001,
          [PrintSide.singleSided]: 430,
          [PrintSide.doubleSided]: 560,
          [PrintSide.singleSidedGlossy]: 0,
          [PrintSide.doubleSidedGlossy]: 0,
        },
      ],
    },
    [PrintColor.normalColor]: {
      [PrintSide.singleSided]: 480,
      [PrintSide.doubleSided]: 620,
      [PrintSide.singleSidedGlossy]: 0,
      [PrintSide.doubleSidedGlossy]: 0,
      breakpoints: [
        {
          at: 501,
          [PrintSide.singleSided]: 460,
          [PrintSide.doubleSided]: 580,
          [PrintSide.singleSidedGlossy]: 0,
          [PrintSide.doubleSidedGlossy]: 0,
        },
        {
          at: 1001,
          [PrintSide.singleSided]: 430,
          [PrintSide.doubleSided]: 560,
          [PrintSide.singleSidedGlossy]: 0,
          [PrintSide.doubleSidedGlossy]: 0,
        },
      ],
    },
    [PrintColor.fullColor]: {
      [PrintSide.singleSided]: 480,
      [PrintSide.doubleSided]: 620,
      [PrintSide.singleSidedGlossy]: 0,
      [PrintSide.doubleSidedGlossy]: 0,
      breakpoints: [
        {
          at: 501,
          [PrintSide.singleSided]: 460,
          [PrintSide.doubleSided]: 580,
          [PrintSide.singleSidedGlossy]: 0,
          [PrintSide.doubleSidedGlossy]: 0,
        },
        {
          at: 1001,
          [PrintSide.singleSided]: 430,
          [PrintSide.doubleSided]: 560,
          [PrintSide.singleSidedGlossy]: 0,
          [PrintSide.doubleSidedGlossy]: 0,
        },
      ],
    },
  },
  [PrintSize.a5]: {
    [PrintColor.blackAndWhite]: {
      [PrintSide.singleSided]: 480,
      [PrintSide.doubleSided]: 620,
      [PrintSide.singleSidedGlossy]: 0,
      [PrintSide.doubleSidedGlossy]: 0,
      breakpoints: [
        {
          at: 501,
          [PrintSide.singleSided]: 460,
          [PrintSide.doubleSided]: 580,
          [PrintSide.singleSidedGlossy]: 0,
          [PrintSide.doubleSidedGlossy]: 0,
        },
        {
          at: 1001,
          [PrintSide.singleSided]: 430,
          [PrintSide.doubleSided]: 560,
          [PrintSide.singleSidedGlossy]: 0,
          [PrintSide.doubleSidedGlossy]: 0,
        },
      ],
    },
    [PrintColor.normalColor]: {
      [PrintSide.singleSided]: 480,
      [PrintSide.doubleSided]: 620,
      [PrintSide.singleSidedGlossy]: 0,
      [PrintSide.doubleSidedGlossy]: 0,
      breakpoints: [
        {
          at: 501,
          [PrintSide.singleSided]: 460,
          [PrintSide.doubleSided]: 580,
          [PrintSide.singleSidedGlossy]: 0,
          [PrintSide.doubleSidedGlossy]: 0,
        },
        {
          at: 1001,
          [PrintSide.singleSided]: 430,
          [PrintSide.doubleSided]: 560,
          [PrintSide.singleSidedGlossy]: 0,
          [PrintSide.doubleSidedGlossy]: 0,
        },
      ],
    },
    [PrintColor.fullColor]: {
      [PrintSide.singleSided]: 480,
      [PrintSide.doubleSided]: 620,
      [PrintSide.singleSidedGlossy]: 0,
      [PrintSide.doubleSidedGlossy]: 0,
      breakpoints: [
        {
          at: 501,
          [PrintSide.singleSided]: 460,
          [PrintSide.doubleSided]: 580,
          [PrintSide.singleSidedGlossy]: 0,
          [PrintSide.doubleSidedGlossy]: 0,
        },
        {
          at: 1001,
          [PrintSide.singleSided]: 430,
          [PrintSide.doubleSided]: 560,
          [PrintSide.singleSidedGlossy]: 0,
          [PrintSide.doubleSidedGlossy]: 0,
        },
      ],
    },
  },
  binding: {
    [BindingType.springNormal]: {
      A4: 1000,
      A3: 2000,
      A5: 500,
    },
    [BindingType.springPapco]: {
      A4: 1500,
      A3: 3000,
      A5: 750,
    },
    [BindingType.stapler]: 3000,
  },
};

export const dedicatedLinkReports: DedicatedLinkReport[] = [
  {
    id: "1",
    date: new Date("2022-07-13T07:24:52"),
    user: users[0],
    customer: users[1],
    orderId: "265454",
    orderAmount: 100000,
    userFee: 0.1,
    userLink: "ref=123",
  },
  {
    id: "2",
    date: new Date("2022-07-13T07:24:52"),
    user: users[0],
    customer: users[1],
    orderId: "265454",
    orderAmount: 100000,
    userFee: 0.1,
    userLink: "ref=123",
  },
  {
    id: "3",
    date: new Date("2022-07-13T07:24:52"),
    user: users[0],
    customer: users[1],
    orderId: "265454",
    orderAmount: 100000,
    userFee: 0.1,
    userLink: "ref=123",
  },
  {
    id: "4",
    date: new Date("2022-07-13T07:24:52"),
    user: users[0],
    customer: users[1],
    orderId: "265454",
    orderAmount: 100000,
    userFee: 0.1,
    userLink: "ref=123",
  },
  {
    id: "5",
    date: new Date("2022-07-13T07:24:52"),
    user: users[0],
    customer: users[1],
    orderId: "265454",
    orderAmount: 100000,
    userFee: 0.1,
    userLink: "ref=123",
  },
];

export const dedicatedDiscountCodeReports: DedicatedDiscountCodeReport[] = [
  {
    id: "1",
    date: new Date("2022-07-13T07:24:52"),
    user: users[0],
    customer: users[1],
    orderId: "265454",
    orderAmount: 100000,
    customerDiscount: 0.1,
    userFee: 0.0,
    discountCode: "HGVFCD",
  },
  {
    id: "2",
    date: new Date("2022-07-13T07:24:52"),
    user: users[0],
    customer: users[1],
    orderId: "265454",
    orderAmount: 100000,
    customerDiscount: 0.1,
    userFee: 0.0,
    discountCode: "HGVFCD",
  },
  {
    id: "3",
    date: new Date("2022-07-13T07:24:52"),
    user: users[0],
    customer: users[1],
    orderId: "265454",
    orderAmount: 100000,
    customerDiscount: 0.05,
    userFee: 0.05,
    discountCode: "NC5WFh",
  },
  {
    id: "4",
    date: new Date("2022-07-13T07:24:52"),
    user: users[0],
    customer: users[1],
    orderId: "265454",
    orderAmount: 100000,
    customerDiscount: 0.05,
    userFee: 0.05,
    discountCode: "NC5WFh",
  },
  {
    id: "5",
    date: new Date("2022-07-13T07:24:52"),
    user: users[0],
    customer: users[1],
    orderId: "265454",
    orderAmount: 100000,
    customerDiscount: 0.1,
    userFee: 0.0,
    discountCode: "HGVFCD",
  },
];

export const customerReports: CustomerReport[] = [
  {
    id: "1",
    user: users[0],
    registrationDate: new Date("2022-07-13T07:24:52"),
    firstOrderDate: new Date("2022-07-13T07:24:52"),
    lastOrderDate: new Date("2022-07-13T07:24:52"),
    totalAmountPaid: 100000,
  },
  {
    id: "2",
    user: users[0],
    registrationDate: new Date("2022-07-13T07:24:52"),
    firstOrderDate: new Date("2022-07-13T07:24:52"),
    lastOrderDate: new Date("2022-07-13T07:24:52"),
    totalAmountPaid: 100000,
  },
  {
    id: "3",
    user: users[0],
    registrationDate: new Date("2022-07-13T07:24:52"),
    firstOrderDate: new Date("2022-07-13T07:24:52"),
    lastOrderDate: new Date("2022-07-13T07:24:52"),
    totalAmountPaid: 100000,
  },
  {
    id: "4",
    user: users[0],
    registrationDate: new Date("2022-07-13T07:24:52"),
    firstOrderDate: new Date("2022-07-13T07:24:52"),
    lastOrderDate: new Date("2022-07-13T07:24:52"),
    totalAmountPaid: 100000,
  },
  {
    id: "5",
    user: users[0],
    registrationDate: new Date("2022-07-13T07:24:52"),
    firstOrderDate: new Date("2022-07-13T07:24:52"),
    lastOrderDate: new Date("2022-07-13T07:24:52"),
    totalAmountPaid: 100000,
  },
];
